[tool.black]
# Match line-length expected by pycodestyle.
line-length = 200
# Current version in Debian trixie.
target-version = ['py313']
# Enable preview features, expected by pycodestyle.
preview = true
